### PR TITLE
Correct coverage header words to include

### PR DESCRIPTION
**Pull request by simonzhaoms**
`coverage: platform linux` should be only valid on Linux.  So I changed `coverage: platform linux` to `coverage: platform`

### CODE REVIEW

**Review by MishaKav — CHANGES_REQUESTED** [review]
can you add please your change in `src/indes.js` > run `npm run all` > `npm version patch`

**Comment by simonzhaoms** [comment]
@MishaKav I got the errors below:

```
$ npm run all

> pytest-coverage-comment@1.1.23 all /repos/pytest-coverage-comment
> npm run lint && npm run format && npm run build


> pytest-coverage-comment@1.1.23 lint /repos/pytest-coverage-comment
> eslint src/**/*.js


Oops! Something went wrong! :(

ESLint: 8.11.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/repos/pytest-coverage-comment/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2383:26)
    at Module._compile (/repos/pytest-coverage-comment/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/repos/pytest-coverage-comment/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/repos/pytest-coverage-comment/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
    at Module._compile (/repos/pytest-coverage-comment/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pytest-coverage-comment@1.1.23 lint: `eslint src/**/*.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the pytest-coverage-comment@1.1.23 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simon/.npm/_logs/2022-03-15T07_58_49_357Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pytest-coverage-comment@1.1.23 all: `npm run lint && npm run format && npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the pytest-coverage-comment@1.1.23 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simon/.npm/_logs/2022-03-15T07_58_49_386Z-debug.log
```

**Review by MishaKav — APPROVED** [review]

**Comment by MishaKav** [comment]
I merged your PR and made all changes.

The feature was released you can just run `MishaKav/pytest-coverage-comment@main` or use `MishaKav/pytest-coverage-comment@v1.1.24`
Thank you.

**Comment by simonzhaoms** [comment]
Thanks @MishaKav

**Pull request merged**
