### PR TITLE
Adding in support for workflow_dispatch events: Take Two

### PR DESCRIPTION
**Pull request by alexjyong**
This PR will allow this action to be used on workflow_dispatch events. The user will be required to pass a PR number via issue-number in the inputs, but this will allow folks to get coverage reports on demand in a github action instead of having to tie it to a pull-request/push event.

I needed this for a work project, so I figured I'd share this with everyone else!

(Re do of https://github.com/MishaKav/pytest-coverage-comment/pull/143 )

### CODE REVIEW

**Comment by alexjyong** [comment]
@MishaKav  I pulled in the latest changes from main on your repo and fixed up the issues you had: https://github.com/MishaKav/pytest-coverage-comment/pull/149

**Review by MishaKav — APPROVED** [review]

**Comment by MishaKav** [comment]
I'm so sorry for bothering you. I still can't build your version.
Try to run `npm run all` after your fix.

image

**Comment by alexjyong** [comment]
@MishaKav  no worries. Strange, I tested this and it worked on my repo. (unfortunately private so I can't share.)

I'll take a look.

**Comment by alexjyong** [comment]
@MishaKav  I had issues with that branch, so I made my PR based off of main instead of that branch. I'll take a closer look though. No idea if that's related though.

**Comment by alexjyong** [comment]
@MishaKav  updated this on: https://github.com/MishaKav/pytest-coverage-comment/pull/150

**Pull request merged**
