### PR TITLE
Add support to coverage XML file.

### PR DESCRIPTION
**Pull request by xportation**
Hi, the coverage output wasn't working for my project, the build wasn't failing.
I'm proposing to support also the coverage XML file. Depending on the file extension, the coverage choose the TXT or the XML report.

### CODE REVIEW

**Comment by MishaKav** [comment]
@xportation Thanks for the PR, it's a little big one, I will check it and let you know.

**Comment by xportation** [comment]
Thanks, @MishaKav.
I tried to separate the `report` logic from the `parsers`.
The `coverage.js` is responsible for the `report` while the `parse.js` continue parsing the TXT console output and the `parseXml.js` parses the XML.

**Comment by hammersbaldthegodofimpacience** [comment]
Hello,

thanks for the nice work. We would like to use this project but requiring the coverage import from XML. Will the PR be merged?

**Comment by paulotruta** [comment]
Supporting XML would be an amazing addition. 

I'm running a mono-repo and I tried using this action with a `.coverage` file resulting from the `coverage combine` command of multiple coverage runs, but I'm getting the following error:

`Error: Error: coverage file "*********" has bad format or wrong data`

I can correctly produce .xml or .lcov files using `coverage xml` and `coverage lcov` respectively, so I'm having trouble understanding why this error happens and if other format would do a better job.

**Comment by MishaKav** [comment]
I will take a look at how to parse coverage from XML in the next few days.

**Comment by hammersbaldthegodofimpacience** [comment]
Any updates here? Can we somehow support for that?

**Comment by MishaKav** [comment]
@xportation huge thanks for the contribution, I merged your changes, fixed bugs and adopted them to all new changes.

now you can all pass `coverage.xml` path like:
 
```yaml
- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-xml-coverage-path: ./coverage.xml
```

**Comment by MishaKav** [comment]
@paulotruta I will be glad if you can test new version of the action:

```yaml
- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-xml-coverage-path: ./coverage.xml
```

**Pull request merged**
