### PR TITLE
Add sample of permissions/Fix permissions of existing jobs

### PR DESCRIPTION
**Pull request by m-tmatma**
Add sample of permissions

### CODE REVIEW

**Review by MishaKav — APPROVED** [review]

**Comment by m-tmatma** [comment]
@MishaKav 
The existing jobs failed, so added/fixed permissions.

**Comment by m-tmatma** [comment]
@MishaKav 
In my actions job, the original permission was OK,
But this PR failed.

So I tried to add `checks: write`.

I used the setting at https://github.com/EnricoMi/publish-unit-test-result-action

**Comment by m-tmatma** [comment]
@MishaKav 
Do you choose `Read and write permissions` in `General` of `Actions` of the repository?

image

**Comment by MishaKav** [comment]
yes, there are the things that I have

image

**Comment by m-tmatma** [comment]
@MishaKav 
https://github.com/m-tmatma/pytest-coverage-comment/pull/4 is PR from my fork to my fork.

https://github.com/m-tmatma/pytest-coverage-comment/actions/runs/8676446011/job/23790962655?pr=4 failed, but it failed at `Create the Badge` which tries to change your gist.
So it is expected to fail in my account.

Please push the branch of this PR to your reposotory, create a PR and check if the PR succeeds.

**Review by MishaKav — APPROVED** [review]

**Comment by m-tmatma** [comment]
thank you for merging

**Comment by MishaKav** [comment]
thank you for your contribution!

**Pull request merged**
