### PR TITLE
Adding in support for workflow_dispatch events

### PR DESCRIPTION
**Pull request by alexjyong**
This PR will allow this action to be used on workflow_dispatch events. The user will be required to pass a PR number via `issue-number` in the inputs, but this will allow folks to get coverage reports on demand in a github action instead of having to tie it to a pull-request/push event. 

I needed this for a work project, so I figured I'd share this with everyone else!

### CODE REVIEW

**Comment by MishaKav** [comment]
great idea! I will take a look in the next few days and make a release for your new feature.

**Comment by alexjyong** [comment]
@MishaKav  Thank you! Let me know if you need anything from me.

**Comment by alexjyong** [comment]
updated some merge conflicts that cropped up.

**Comment by alexjyong** [comment]
Ah I see this got folded in another PR. anything else needed from here or can we close this?

**Comment by MishaKav** [comment]
@alexjyong I tried to bump a new version and release your feature, but it can't build successfully, because you have `Parsing error: Unexpected token else`
Can you please provide a fix for that? This is the branch with your changes https://github.com/MishaKav/pytest-coverage-comment/compare/support-pr-in-workflow-dispatch?expand=1
image

**Comment by alexjyong** [comment]
Sure thing.

**Pull request merged**
