### PR TITLE
Correct typos & error messages

### PR DESCRIPTION
**Pull request by gs11**
This PR corrects some minor typos and error messages.

Thank you for a great action!

### CODE REVIEW

**Review by MishaKav — CHANGES_REQUESTED** [review]
Thanks for the update.
Can you please run `npm i && npm run all` for build and commit the changes

**Comment by gs11** [comment]
> Thanks for the update. Can you please run `npm i && npm run all` for build and commit the changes

No problem, done!

**Comment by MishaKav** [comment]
Is it ok If I will just merge your changes to `master` and will release a new version on next update?

**Comment by gs11** [comment]
Of course :) Consider this PR very minor

**Review by MishaKav — APPROVED** [review]

**Pull request merged**
